# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchestra" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "0853ac49aa3c9a9ef95d67a004a90b0138067916ee00eba5f4ade8141ef532ce"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef7650b8efa863dbf5c236146cdf74cab29fc5dcb93b792204664d7042b56849"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25021a4d4a1cc7f5dd9f871fea5984d5eb9a206da299dd591a1be8785f52e3fb"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fee4373fd37ae059b93aaf8349bf9e6cc863cd7d73ac5e764a5cbe27f09f9c49"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orchestra"
  desc "The operating system for AI coding agents"
  homepage "https://github.com/crossben/orchestra-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchestra"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchestra"]
    end
  end

  # No zap stanza required
end
