# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchestra" do
  version "0.7.3"

  on_macos do
    on_intel do
      sha256 "0b79cc563d05c883e691eb384308382c39750855f67ff0b355c798f8bc3c405d"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c9371c63c38f15a1dedb094eb3072b3887d0c9a26fe76f61da8919fdb86c909"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2999b09f797f45e054f1838606ece3b2abafa81cafac52efe7b4f838c4a0d6ad"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "635ff2b52d6e78801c9f05d14c4ceed37e40f3c2c50b535e7b4cd025bffea1aa"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orchestra"
  desc "The operating system for AI coding agents"
  homepage "https://github.com/crossben/orchestra-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchestra"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchestra"]
    end
  end

  # No zap stanza required

end
