# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchestra" do
  version "0.9.2"

  on_macos do
    on_arm do
      sha256 "f825820c0df73cdc2fd4a2e86d2a5d516ca19f4aa3c72e6d5938b82848f20b64"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf29b9001a4ab0b57bc81752582fc28d638e3d62673899c30fd114b2dd115b39"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "429987a7652a20c280fca6a266ab2754fa8e3f6eb1c55ae04d6d703f892b375e"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "322ecd50a5d22418eb52345bc3e69f54f3b474fcc42b795c746e6f0b1ff1f9f4"
      url "https://github.com/crossben/orchestra-code/releases/download/v#{version}/orchestra_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orchestra"
  desc "The operating system for AI coding agents"
  homepage "https://github.com/crossben/orchestra-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchestra"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchestra"]
    end
  end

  # No zap stanza required
end
